name: Build
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          cache-hash: ${{ hashFiles('**/deno.json') }}
      - run: deno test
      - run: deno lint
      - run: deno doc --lint *.ts
